### ISSUE TITLE
Add noscroll on body when overlay-view is displayed

### ISSUE THREAD

**Issue by napanee** [moccu/picnic#15]

**Comment by schorfES** [comment]
This should be done optionally. Maybe when clickblocker is displayed.

**Comment by Schascha** [comment]
Branch: https://github.com/moccu/picnic/tree/feature/overlay-noscroll

We can add overflow hidden to the body element on the overlay open, see b5b93e7

Maybe the better solution is to add an optional class to the target element:

`
.has-open-overlay {
  overflow: hidden;
}
`

**Comment by schorfES** [comment]
@jnnkm did a lot of work here in #26 but there are some todos open to finally merge it into master.

**Comment by Schascha** [comment]
Thanks, I did not recognize this feature. All in all I propose to add the open class at the target element. I will remove [feature/overlay-noscroll](https://github.com/moccu/picnic/tree/feature/overlay-noscroll) after #26 is finally merged.

**Comment by schorfES** [comment]
Solved in [0.7.0](https://github.com/moccu/picnic/releases/tag/0.7.0)
